// test/invariants/pokemon-intl-namespacing.test.mjs
//
// Non-English Pokémon identity keys carry their TCGdex lane ('ja:m5-102'). This file exists because
// that looks like a naming convention and is not one — it is the only thing keeping three different
// cards apart, and the reason is data, not taste. So the test PROVES the collision it guards
// against rather than asserting the convention.
//
// Two independent properties:
//   1. A namespaced key can never be read as a set id, so it can never become a cache FILENAME and
//      can never be served out of the English card cache.
//   2. The printed set codes really do collide — across languages, and against pokemontcg.io.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isSetId } from '../../lib/set-cache.mjs';
import { lookupPath, pricePath } from '../../lib/normalize.mjs';
import { intlIdentityKey, intlKeyLang, INTL_DATA_LANGS } from '../../lib/pokemon-intl.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const readJson = (p) => { try { return JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8')); } catch { return null; } };

// How lib/pkm-cards-cache.mjs splits an identity key into (setId, number) before deciding whether
// it may answer from disk. Reproduced rather than imported because what is under test is the shape
// of the key, not that function.
const setIdPartOf = (key) => { const i = String(key).lastIndexOf('-'); return i < 0 ? String(key) : String(key).slice(0, i); };

describe('a namespaced key cannot reach the English card cache', () => {
  const keys = [
    intlIdentityKey('ja', 'M5', '102'),
    intlIdentityKey('ja', 'SV3', '001'),
    intlIdentityKey('zh-tw', 'SV8A', '102'),
    intlIdentityKey('zh-cn', 'CSV4C', '011'),
    intlIdentityKey('ko', 'SV6', '045'),
  ];

  it('is rejected by isSetId once split the way the cache splits it', () => {
    for (const k of keys) {
      assert.ok(k, 'intlIdentityKey returned nothing');
      assert.equal(isSetId(setIdPartOf(k)), false, `${k} -> ${setIdPartOf(k)} is a usable set id`);
    }
  });

  // The colon is what does it. If someone "tidies" the separator to a hyphen or a dot, this fails
  // — which is the point, because SET_ID_RE allows both and the cache would start answering.
  it('is the COLON that makes it impossible, not the prefix', () => {
    for (const k of keys) assert.ok(k.includes(':'), k);
    assert.equal(isSetId('ja-m5'), true, 'a hyphen separator WOULD pass isSetId — do not use one');
    assert.equal(isSetId('ja.m5'), true, 'a dot separator WOULD pass isSetId — do not use one');
    assert.equal(isSetId('ja:m5'), false);
  });

  // pokemontcg.io holds no such card, so there is no record path and therefore no price path. The
  // null is what stops the collector filing an intl row as a price failure it can never fix.
  it('has no pokemontcg.io lookup or price path', () => {
    for (const k of keys) {
      assert.equal(lookupPath('pokemon', k), null, k);
      assert.equal(pricePath('pokemon', k), null, k);
    }
  });

  it('leaves English keys exactly as they were', () => {
    assert.equal(lookupPath('pokemon', 'sv3-102'), '/api/pkm/cards/sv3-102');
    assert.equal(pricePath('pokemon', 'sv3-102'), '/api/pkm/cards/sv3-102');
    assert.equal(intlKeyLang('sv3-102'), null);
    assert.equal(isSetId(setIdPartOf('sv3-102')), true);
  });
});

// The bakes are gitignored build artifacts (regenerated by lib/refresh.mjs and on first boot), so
// these read them when present and say so when not. The property above holds regardless; what is
// conditional is only the evidence for WHY it matters.
describe('the collision these keys exist to prevent is real', () => {
  const intl = readJson('data/pokemon-intl-sets.json');
  // lib/set-cache.mjs stores { at, body } and the body is the pokemontcg.io envelope, so the ids
  // are two unwraps down. Tolerant of every shape rather than pinned to one: this is a runtime
  // cache, and a test that fails because a cache format moved is noise, not a finding.
  const enCache = readJson('data/pkm-cache/sets.json');
  const enList = (() => {
    for (const c of [enCache, enCache && enCache.body, enCache && enCache.body && enCache.body.data, enCache && enCache.data]) {
      if (Array.isArray(c)) return c;
    }
    return [];
  })();
  const enIds = new Set(enList.map((s) => String((s && s.id) || '').toUpperCase()).filter(Boolean));

  it('the same printed set code is reused across intl languages', { skip: !intl && 'data/pokemon-intl-sets.json not baked' }, () => {
    const seen = new Map();
    for (const dl of INTL_DATA_LANGS) {
      for (const s of intl[dl] || []) {
        const code = String(s.code || '').toUpperCase();
        if (!code) continue;
        if (!seen.has(code)) seen.set(code, new Set());
        seen.get(code).add(dl);
      }
    }
    const shared = [...seen.entries()].filter(([, langs]) => langs.size > 1);
    assert.ok(shared.length > 0,
      'no intl set code is shared across languages — if this is genuinely true now, the namespacing is still correct but this test no longer proves it');
    // Korean and Traditional-Chinese sets ARE Japanese sets translated, so they reuse the code.
    const [code, langs] = shared[0];
    assert.ok(intlIdentityKey([...langs][0], code, '102') !== intlIdentityKey([...langs][1], code, '102'),
      `${code} is printed in ${[...langs].join(' + ')} and both would key the same without the lane`);
  });

  it('intl set codes collide with pokemontcg.io set ids', { skip: (!intl || !enIds.size) && 'set catalogues not cached' }, () => {
    const clashes = [];
    for (const dl of INTL_DATA_LANGS) {
      for (const s of intl[dl] || []) {
        const code = String(s.code || '').toUpperCase();
        if (code && enIds.has(code)) clashes.push(`${dl}:${code}`);
      }
    }
    assert.ok(clashes.length > 0,
      'no intl code matches a pokemontcg.io set id — the namespacing is still correct, but re-check this test');
    // e.g. Japanese SV3 and English sv3 (Obsidian Flames) are different sets with the same code,
    // and /api/inventory/match selects on identity_key with no game or language filter.
    const [lang, code] = clashes[0].split(':');
    assert.notEqual(intlIdentityKey(lang, code, '102'), `${code.toLowerCase()}-102`);
  });
});
