// test/unit/listing-title-parse.test.mjs — reading a card back out of a listing title.
//
// The strongest check here is the ROUND TRIP: titles are generated by this repo's own
// titleParts()/fitTitle(), so feeding buildTitle's output back through the parser must recover the
// card. That also exercises the lossy path — over 80 characters fitTitle abbreviates and then drops
// tokens outright, so the parser has to cope with "Pokemon", the language and the condition simply
// not being there.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildTitle } from '../../lib/listing-copy.mjs';
import { parseCardTitle, findNumber, findSet, findGrade, findFinish, normSet } from '../../lib/listing-title-parse.mjs';

// A realistic slice of the EN set list, including the pairs that make naive matching fail.
const SETS = [
  { id: 'swsh11', name: 'Lost Origin' }, { id: 'sv9', name: 'Journey Together' },
  { id: 'base1', name: 'Base Set' }, { id: 'sv3pt5', name: '151' },
  { id: 'swsh12pt5', name: 'Crown Zenith' }, { id: 'sv8', name: 'Surging Sparks' },
  { id: 'sm12', name: 'Cosmic Eclipse' }, { id: 'swsh9', name: 'Brilliant Stars' },
];

describe('parseCardTitle — the two real listings that started this', () => {
  it('reads the hand-made Wailord listing', () => {
    const p = parseCardTitle('Pokemon Wailord 162/159 Journey Together Illustration Rare Holo EN M/NM', { setNames: SETS });
    assert.equal(p.name, 'Wailord');
    assert.equal(p.number, '162/159');
    assert.equal(p.setId, 'sv9');
    assert.equal(p.finish, 'Holo');
    assert.equal(p.condition, 'Near Mint');
    assert.equal(p.identityGuess, 'sv9-162');
    assert.equal(p.graded, false);
  });

  it('reads the tool-made Radiant Gardevoir listing, zero-padding and all', () => {
    const p = parseCardTitle('Pokemon Radiant Gardevoir 069/196 Lost Origin Radiant Rare Holo EN M/NM', { setNames: SETS });
    assert.equal(p.name, 'Radiant Gardevoir');
    assert.equal(p.setId, 'swsh11');
    assert.equal(p.identityGuess, 'swsh11-69', 'the pokemontcg.io id drops the leading zeros');
  });
});

describe('round trip against the repo\'s own title builder', () => {
  const cards = [
    { f: { name: 'Wailord', num: '162/159', set: 'Journey Together', rarity: 'Illustration Rare', finish: 'Holo', lang: 'English', cond: 'Near Mint' }, want: 'sv9-162' },
    { f: { name: 'Radiant Gardevoir', num: '069/196', set: 'Lost Origin', rarity: 'Radiant Rare', finish: 'Holo', lang: 'English', cond: 'Near Mint' }, want: 'swsh11-69' },
    { f: { name: 'Charizard', num: '4/102', set: 'Base Set', rarity: 'Holo Rare', finish: 'Holofoil', lang: 'English', cond: 'Lightly Played', edition: '1st Edition' }, want: 'base1-4' },
    { f: { name: 'Pikachu', num: '025/165', set: '151', rarity: 'Common', finish: 'Reverse Holofoil', lang: 'English', cond: 'Near Mint' }, want: 'sv3pt5-25' },
    // Long enough that fitTitle has to abbreviate and drop tokens.
    { f: { name: 'Mimikyu ex Special Delivery', num: '199/197', set: 'Brilliant Stars', rarity: 'Special Illustration Rare', finish: 'Reverse Holofoil', lang: 'English', cond: 'Moderately Played' }, want: 'swsh9-199' },
  ];

  for (const c of cards) {
    it('recovers ' + c.f.name + ' from its generated title', () => {
      const title = buildTitle('pokemon', c.f);
      assert.ok(title.length <= 80, 'the builder caps at 80: ' + title.length);
      const p = parseCardTitle(title, { setNames: SETS });
      assert.equal(p.identityGuess, c.want, 'from title: ' + title);
      assert.ok(p.name && c.f.name.startsWith(p.name.split(' ')[0]), 'name survived: ' + p.name);
    });
  }

  it('still finds the identity when the title is squeezed hard', () => {
    // 80-char pressure drops the language, condition and even "Pokemon" — the set and number are
    // higher priority and survive, which is exactly what the identity needs.
    const t = buildTitle('pokemon', { name: 'Iron Valiant ex Ultra Premium Collection Promo', num: '089/182',
      set: 'Cosmic Eclipse', rarity: 'Special Illustration Rare', finish: 'Reverse Holofoil', lang: 'English', cond: 'Near Mint' });
    const p = parseCardTitle(t, { setNames: SETS });
    assert.equal(p.identityGuess, 'sm12-89', 'from squeezed title: ' + t);
  });
});

describe('the pieces, and what they refuse to guess', () => {
  it('prefers the longest matching set name', () => {
    const sets = [{ id: 'a', name: 'Lost Origin' }, { id: 'b', name: 'Sword & Shield - Lost Origin' }];
    assert.equal(findSet('Pokemon X 1/196 Sword & Shield - Lost Origin Holo', sets).id, 'b');
  });
  it('matches set names across punctuation differences', () => {
    assert.equal(normSet("Champion's Path"), 'champions path');
    assert.equal(findSet('Pokemon Charizard V 79/73 Champions Path Holo', [{ id: 'swsh35', name: "Champion's Path" }]).id, 'swsh35');
  });
  it('finds a promo code when there is no fraction', () => {
    assert.equal(findNumber('Pokemon Pikachu SWSH123 Black Star Promo').printed, 'SWSH123');
  });
  it('reads a graded slab and does not also report a raw condition', () => {
    const p = parseCardTitle('Pokemon Charizard 4/102 Base Set PSA 10 GEM MT', { setNames: SETS });
    assert.equal(p.graded, true);
    assert.equal(p.grading_company, 'PSA');
    assert.equal(p.grade, 10);
    assert.equal(p.condition, null);
  });
  it('tells Reverse Holo from Holo', () => {
    assert.equal(findFinish('x Reverse Holo y'), 'Reverse Holo');
    assert.equal(findFinish('x RH y'), 'Reverse Holo');
    assert.equal(findFinish('x Holo y'), 'Holo');
  });
  it('gives up honestly rather than inventing an identity', () => {
    const p = parseCardTitle('Bulk lot of 100 assorted Pokemon cards', { setNames: SETS });
    assert.equal(p.identityGuess, null);
    assert.equal(p.confidence, 'none');
    assert.ok(p.missing.includes('number') || p.missing.includes('set'));
  });
  it('cannot be better than low confidence with no set list to match against', () => {
    const p = parseCardTitle('Pokemon Wailord 162/159 Journey Together Holo EN M/NM');
    assert.equal(p.setId, null);
    assert.equal(p.confidence, 'none');
  });
  it('finds no grade in a title that merely mentions a number', () => {
    assert.equal(findGrade('Pokemon Wailord 162/159 Journey Together'), null);
  });
});
