// test/unit/listing-title-parse.test.mjs — reading a card back out of a listing title.
//
// The strongest check here is the ROUND TRIP: titles are generated by this repo's own
// titleParts()/fitTitle(), so feeding buildTitle's output back through the parser must recover the
// card. That also exercises the lossy path — over 80 characters fitTitle abbreviates and then drops
// tokens outright, so the parser has to cope with "Pokemon", the language and the condition simply
// not being there.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { buildTitle } from '../../lib/listing-copy.mjs';
import { parseCardTitle, findNumber, findSet, findGrade, findFinish, normSet } from '../../lib/listing-title-parse.mjs';
import { buildNumberRe } from '../../lib/comps-singles.mjs';

// A realistic slice of the EN set list, including the pairs that make naive matching fail.
const SETS = [
  { id: 'swsh11', name: 'Lost Origin' }, { id: 'sv9', name: 'Journey Together' },
  { id: 'base1', name: 'Base Set' }, { id: 'sv3pt5', name: '151' },
  { id: 'swsh12pt5', name: 'Crown Zenith' }, { id: 'sv8', name: 'Surging Sparks' },
  { id: 'sm12', name: 'Cosmic Eclipse' }, { id: 'swsh9', name: 'Brilliant Stars' },
];

describe('parseCardTitle — the two real listings that started this', () => {
  it('reads the hand-made Wailord listing', () => {
    const p = parseCardTitle('Pokemon Wailord 162/159 Journey Together Illustration Rare Holo EN M/NM', { setNames: SETS });
    assert.equal(p.name, 'Wailord');
    assert.equal(p.number, '162/159');
    assert.equal(p.setId, 'sv9');
    assert.equal(p.finish, 'Holo');
    assert.equal(p.condition, 'Near Mint');
    assert.equal(p.identityGuess, 'sv9-162');
    assert.equal(p.graded, false);
  });

  it('reads the tool-made Radiant Gardevoir listing, zero-padding and all', () => {
    const p = parseCardTitle('Pokemon Radiant Gardevoir 069/196 Lost Origin Radiant Rare Holo EN M/NM', { setNames: SETS });
    assert.equal(p.name, 'Radiant Gardevoir');
    assert.equal(p.setId, 'swsh11');
    assert.equal(p.identityGuess, 'swsh11-69', 'the pokemontcg.io id drops the leading zeros');
  });
});

describe('round trip against the repo\'s own title builder', () => {
  const cards = [
    { f: { name: 'Wailord', num: '162/159', set: 'Journey Together', rarity: 'Illustration Rare', finish: 'Holo', lang: 'English', cond: 'Near Mint' }, want: 'sv9-162' },
    { f: { name: 'Radiant Gardevoir', num: '069/196', set: 'Lost Origin', rarity: 'Radiant Rare', finish: 'Holo', lang: 'English', cond: 'Near Mint' }, want: 'swsh11-69' },
    { f: { name: 'Charizard', num: '4/102', set: 'Base Set', rarity: 'Holo Rare', finish: 'Holofoil', lang: 'English', cond: 'Lightly Played', edition: '1st Edition' }, want: 'base1-4' },
    { f: { name: 'Pikachu', num: '025/165', set: '151', rarity: 'Common', finish: 'Reverse Holofoil', lang: 'English', cond: 'Near Mint' }, want: 'sv3pt5-25' },
    // Long enough that fitTitle has to abbreviate and drop tokens.
    { f: { name: 'Mimikyu ex Special Delivery', num: '199/197', set: 'Brilliant Stars', rarity: 'Special Illustration Rare', finish: 'Reverse Holofoil', lang: 'English', cond: 'Moderately Played' }, want: 'swsh9-199' },
  ];

  for (const c of cards) {
    it('recovers ' + c.f.name + ' from its generated title', () => {
      const title = buildTitle('pokemon', c.f);
      assert.ok(title.length <= 80, 'the builder caps at 80: ' + title.length);
      const p = parseCardTitle(title, { setNames: SETS });
      assert.equal(p.identityGuess, c.want, 'from title: ' + title);
      assert.ok(p.name && c.f.name.startsWith(p.name.split(' ')[0]), 'name survived: ' + p.name);
    });
  }

  it('still finds the identity when the title is squeezed hard', () => {
    // 80-char pressure drops the language, condition and even "Pokemon" — the set and number are
    // higher priority and survive, which is exactly what the identity needs.
    const t = buildTitle('pokemon', { name: 'Iron Valiant ex Ultra Premium Collection Promo', num: '089/182',
      set: 'Cosmic Eclipse', rarity: 'Special Illustration Rare', finish: 'Reverse Holofoil', lang: 'English', cond: 'Near Mint' });
    const p = parseCardTitle(t, { setNames: SETS });
    assert.equal(p.identityGuess, 'sm12-89', 'from squeezed title: ' + t);
  });
});

describe('the pieces, and what they refuse to guess', () => {
  it('prefers the longest matching set name', () => {
    const sets = [{ id: 'a', name: 'Lost Origin' }, { id: 'b', name: 'Sword & Shield - Lost Origin' }];
    assert.equal(findSet('Pokemon X 1/196 Sword & Shield - Lost Origin Holo', sets).id, 'b');
  });
  it('matches set names across punctuation differences', () => {
    assert.equal(normSet("Champion's Path"), 'champions path');
    assert.equal(findSet('Pokemon Charizard V 79/73 Champions Path Holo', [{ id: 'swsh35', name: "Champion's Path" }]).id, 'swsh35');
  });
  it('finds a promo code when there is no fraction', () => {
    assert.equal(findNumber('Pokemon Pikachu SWSH123 Black Star Promo').printed, 'SWSH123');
  });
  it('reads a graded slab and does not also report a raw condition', () => {
    const p = parseCardTitle('Pokemon Charizard 4/102 Base Set PSA 10 GEM MT', { setNames: SETS });
    assert.equal(p.graded, true);
    assert.equal(p.grading_company, 'PSA');
    assert.equal(p.grade, 10);
    assert.equal(p.condition, null);
  });
  it('tells Reverse Holo from Holo', () => {
    assert.equal(findFinish('x Reverse Holo y'), 'Reverse Holo');
    assert.equal(findFinish('x RH y'), 'Reverse Holo');
    assert.equal(findFinish('x Holo y'), 'Holo');
  });
  it('gives up honestly rather than inventing an identity', () => {
    const p = parseCardTitle('Bulk lot of 100 assorted Pokemon cards', { setNames: SETS });
    assert.equal(p.identityGuess, null);
    assert.equal(p.confidence, 'none');
    assert.ok(p.missing.includes('number') || p.missing.includes('set'));
  });
  it('cannot be better than low confidence with no set list to match against', () => {
    const p = parseCardTitle('Pokemon Wailord 162/159 Journey Together Holo EN M/NM');
    assert.equal(p.setId, null);
    assert.equal(p.confidence, 'none');
  });
  it('finds no grade in a title that merely mentions a number', () => {
    assert.equal(findGrade('Pokemon Wailord 162/159 Journey Together'), null);
  });
});

// --- hash-prefixed collector numbers ------------------------------------------------------------
// Magic and Star Wars Unlimited titles write the number as "#160". Nothing read them before, so all
// 10 MTG listings in the live store parsed to number:null and the repricer refused every one of
// them as title_unparseable. The pattern is tried LAST, after the slash and promo forms, so it can
// only ever reach titles that already returned null.
describe('findNumber — "#160", the Magic and Star Wars Unlimited shape', () => {
  it('reads a hash number and stores it bare, without the hash', () => {
    // Bare, because buildNumberRe and the comps query both consume the digits, not the punctuation.
    const n = findNumber('Living End (Silver Scroll) - Strixhaven Mystical Archive (SOA) #160 MTG NM/M');
    assert.equal(n.printed, '160');
    assert.equal(n.numerator, '160');
    assert.equal(n.denominator, null);
    assert.equal(n.hash, true);
  });
  it('copes with no space before the trailing letters ("#107MTG" — a real title)', () => {
    assert.equal(findNumber('Crackle with Power (JP Alt Art) - Strixhaven Mystical Archive (SOA) #107MTG NM/M').printed, '107');
  });
  it('reads the Star Wars Unlimited form too', () => {
    assert.equal(findNumber('Chirrut Imwe - One With The Force (Showcase) SWU #256 - Spark of Rebellion (SOR)').printed, '256');
  });
  it('takes a two-digit number', () => {
    assert.equal(findNumber("Sheoldred's Edict (JP Alt Art) - Strixhaven Mystical Archive (SOA) #97 MTG NM/M").printed, '97');
  });

  // The hash also introduces the things a title says about the SALE rather than the card.
  it('refuses a grading cert, which is far too long to be a collector number', () => {
    assert.equal(findNumber('Charizard Base Set PSA 10 cert #12345678'), null);
  });
  it('refuses the sale words that take a hash', () => {
    for (const t of ['Bulk lot #3 of assorted cards', 'Pokemon order #12 replacement', 'Spare item #7']) {
      assert.equal(findNumber(t), null, t);
    }
  });
  it('still reads a graded card whose own number is hashed', () => {
    // "PSA" appears, but not immediately before the hash — the blocklist looks at the word next to
    // it, so a real number is not thrown away just because the card is graded.
    assert.equal(findNumber('PSA 10 Charizard #4 Base Set Shadowless').printed, '4');
  });
  it('skips a blocked hash and keeps looking for a real one', () => {
    assert.equal(findNumber('Order #55 - Living End (SOA) #160 MTG').printed, '160');
  });

  // Tried last, so nothing that parsed before can change shape.
  it('never displaces a slash number or a promo code', () => {
    assert.equal(findNumber('Pokemon Wailord ex 016/084 Pitch Black #99').printed, '016/084');
    assert.equal(findNumber('Pokemon Zacian SWSH123 promo #99').printed, 'SWSH123');
  });
  it('leaves the card name free of the dangling hash', () => {
    const p = parseCardTitle('Living End (Silver Scroll) - Strixhaven Mystical Archive (SOA) #160 MTG NM/M');
    assert.equal(p.number, '160');
    assert.ok(!p.name.endsWith('#'), 'name should not trail a hash: ' + JSON.stringify(p.name));
  });
});

// --- the shapes that were 54 of 154 live listings ------------------------------------------------
// A third of the catalogue was never priced at all because findNumber only understood N/M, a promo
// code, and (since the last change) #N. Lorcana prints no denominator, Japanese Pokémon promos print
// none either, Riftbound alt arts carry a letter, and Star Wars Unlimited puts a SET CODE where the
// total belongs.
describe('findNumber — the remaining live shapes', () => {
  it('reads an alt-art letter as part of the number, not decoration', () => {
    const n = findNumber('Jinx - Demolitionist (Alt Art) 030a/298 Riftbound Origins (OGN) ENGLISH SHOWCASE');
    assert.equal(n.printed, '030a/298');
    assert.equal(n.numerator, '030a');
  });
  it('reads a set code as the denominator (Star Wars Unlimited)', () => {
    assert.equal(findNumber('Command 107/SOR - Star Wars Unlimited Spark of Rebellion (SOR) EN LEGENDARY').printed, '107/SOR');
  });
  it('reads a bare number when there is no denominator at all', () => {
    assert.equal(findNumber('Dale - Ready for His Shot 22 - Disney Lorcana Wilds Unknown (12) EN LEG M/NM').printed, '22');
    assert.equal(findNumber('Pokemon Dhelmise 88 Abyss Eye Art Rare Holo JP M/NM').printed, '88');
    assert.equal(findNumber('Order Rune 214a (Alt Art) - Riftbound Origins (OGN) ENGLISH SHOWCASE NM/M').printed, '214a');
  });

  // A bare number is the weakest signal here, so what it REFUSES is most of its value.
  it('refuses a single digit — it would match a fifth of all titles', () => {
    assert.equal(findNumber('Pikachu 5 Promo'), null);
  });
  it('refuses a year', () => {
    assert.equal(findNumber('Charizard 2026 Anniversary Holo'), null);
  });
  it('refuses a quantity', () => {
    assert.equal(findNumber('Bulk 25x assorted holo cards'), null);
    assert.equal(findNumber('Assorted holo cards x 25'), null);
  });
  it('refuses a parenthesised set ordinal, which Lorcana titles end with', () => {
    assert.equal(findNumber('Kristoff - Reindeer Keeper - Disney Lorcana Promo (12)'), null);
  });
  it('does NOT read "ex" as a quantity — that swallowed every ex card', () => {
    // The guard used to be a bare trailing "x", so "Mega Darkrai ex 99" and "Dustox 195" both looked
    // like quantities and five real listings went unpriced.
    assert.equal(findNumber('Pokemon Mega Darkrai ex 99 Abyss Eye Super Rare Holo JP M/NM').printed, '99');
    assert.equal(findNumber('Pokemon Dustox 195 Mega Dream ex Art Rare Holo JP M/NM').printed, '195');
    assert.equal(findNumber('Pokemon Mega Floette Ex 99 Ninja Spinner Super Rare Holo JP M/NM').printed, '99');
  });
  it('is still the LAST resort — a better-formed number always wins', () => {
    assert.equal(findNumber('Pokemon Wailord ex 016/084 Pitch Black 99').printed, '016/084');
    assert.equal(findNumber('Pokemon Zacian SWSH123 promo 99').printed, 'SWSH123');
    assert.equal(findNumber('Living End (SOA) #160 MTG 99').printed, '160');
  });
});

describe('buildNumberRe — the alt art and the base card are different cards', () => {
  it('does not cross-match in either direction', () => {
    // The old regex compiled 030a/298 to /\b0*30\b/, which missed the card's own title and matched
    // the base card's — it excluded every correct comp and admitted the wrong ones.
    const alt = buildNumberRe('030a/298'), base = buildNumberRe('030/298');
    assert.equal(alt.test('Jinx - Demolitionist (Alt Art) 030a/298'), true);
    assert.equal(alt.test('Jinx - Demolitionist 030/298'), false);
    assert.equal(base.test('Jinx - Demolitionist 030/298'), true);
    assert.equal(base.test('Jinx - Demolitionist (Alt Art) 030a/298'), false);
  });
  it('keeps zero-padding tolerance on both sides', () => {
    assert.equal(buildNumberRe('016/084').test('Wailord ex 16/84 Pitch Black'), true);
    assert.equal(buildNumberRe('16/84').test('Wailord ex 016/084 Pitch Black'), true);
  });
  it('matches a lettered denominator literally', () => {
    assert.equal(buildNumberRe('107/SOR').test('Command 107/SOR - Star Wars Unlimited'), true);
    assert.equal(buildNumberRe('107/SOR').test('Command 107/999 - something else'), false);
  });
  it('a bare number still needs a word boundary', () => {
    assert.equal(buildNumberRe('88').test('Card 88 Set'), true);
    assert.equal(buildNumberRe('88').test('Card 880 Set'), false);
    assert.equal(buildNumberRe('214a').test('Order Rune 214a Alt Art'), true);
    assert.equal(buildNumberRe('214a').test('Order Rune 214 base'), false);
  });
});
